---
- hosts: all
  become: yes
  become_user: ubuntu
  gather_facts: no

  tasks:
    - name: pull branch master
      git:
        repo: "{{ repo_url }}/{{ repo }}.git"
        dest: "{{ repo_dir }}"
        accept_hostkey: yes

    - name: Create virtual environment
      command: python3 -m venv venv
      args:
        chdir: "{{ repo_dir }}"

    - name: Install python requirements
      pip:
        requirements: "{{ repo_dir }}/requirements.txt"
        state: present
        executable: "{{ repo_dir }}/venv/bin/pip"

    - name: Create gunicorn_config.py
      template:
        src: gunicorn_config.py.j2  # Assuming you have a Jinja2 template file
        dest: "{{ repo_dir }}/gunicorn_config.py"
      vars:
        gunicorn_bind: "0.0.0.0:9876"
        gunicorn_workers: 4

    - debug:
        var: result.stdout_lines

