---
- name: Set environment variables on hosts
  hosts: all
  become: true
  become_user: ubuntu
  tasks:
    - name: Copy env file to hosts
      copy:
        src: .env
        dest: /home/ubuntu/todolist-flask/.env
        mode: 0644
