---
- name: Deploy and run Flask application
  hosts: all
  become: yes

  tasks:
    - name: Change into the 'todolist-flask' directory
      become_user: ubuntu
      shell: cd /home/ubuntu/todolist-flask
      args:
        chdir: /home/ubuntu/todolist-flask  # Ensures the directory change is persistent

    - name: Debug message for directory change
      debug:
        msg: "Changed directory to /home/ubuntu/todolist-flask"

    - name: Run Flask application with nohup
      become_user: root
      shell: sudo nohup python3 todo.py > /dev/null 2>&1 &
      async: 0
      poll: 0

    - name: Debug message for running Flask application
      debug:
        msg: "Running Flask application with nohup command"

  handlers:
    - name: Wait for Flask application to start
      become_user: root
      wait_for:
        host: localhost
        port: 80
        state: started
        delay: 5
        timeout: 60

