---
- hosts: all
  become: yes
  become_user: root
  gather_facts: no
  tasks:
    - name: Activate virtual environment and install Gunicorn
      ansible.builtin.command: >
        /home/ubuntu/todolist-flask/venv/bin/python -m pip install gunicorn

    # - name: Install Gunicorn Python package
    #   pip:
    #     name: gunicorn
    #     executable: /home/ubuntu/todolist-flask/venv/bin/pip  # Specify the path to your venv's pip

    - name: Copy Gunicorn systemd service file
      template:
        src: todolist-flask.service
        dest: /etc/systemd/system/todolist-flask.service
      register: gunicorn_service

    - name: Enable and start Gunicorn service
      systemd:
        name: todolist-flask
        state: started
        enabled: yes
      # when: gunicorn_service.changed
      notify:
        - Restart Gunicorn

    - name: Ensure execute permissions for gunicorn_config.py
      file:
        path: /home/ubuntu/todolist-flask/gunicorn_config.py
        mode: '+x'
      register: gunicorn_config_permissions

    - name: Restart Gunicorn
      systemd:
        name: todolist-flask
        state: restarted
      when: gunicorn_service.changed or gunicorn_config_permissions.changed

  handlers:
    - name: Restart Gunicorn
      systemd:
        name: todolist-flask
        state: restarted

